name: Flutter Web Deploy

on:
  push:
    branches: [ master ]  # Assuming your main branch is named master
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'  # Using the version suggested in the error message
          channel: 'stable'
          
      - name: Install dependencies
        run: |
          cd dart_rpg
          flutter pub get
          
      - name: Build web app
        run: |
          cd dart_rpg
          flutter build web --release --base-href /DartRPG/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dart_rpg/build/web
          force_orphan: true  # This will make the gh-pages branch have only the latest commit
